// CREATE AN ARRAY OF OBJECTS AND MAP TO THE DOM

// SLECT ALL CHECKBOXES AND OUTPUT THE SLECTED CHECKBOX VALUE

// CREATE A FRUIT BASKET OBJECT AND INCREMENT - 
//      i. THE VALUES OF THE OBJECT
//      ii. THE VALUES OF THE INPUT VALUE